"""Add initial tables set

Revision ID: 3a72a95259da
Revises: 
Create Date: 2019-05-10 00:05:45.355126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a72a95259da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('name_variants', sa.ARRAY(sa.String(length=255)), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maker',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('url', sa.String(length=255), nullable=False),
        sa.Column('parser_cls', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('maker_id', sa.Integer(), nullable=True),
        sa.Column('sku', sa.String(length=255), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('name_variants', sa.ARRAY(sa.String(length=255)), nullable=True),
        sa.ForeignKeyConstraint(('maker_id',), ['maker.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=False)
    op.create_table('product_component',
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('component_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(('component_id',), ['component.id'], ),
        sa.ForeignKeyConstraint(('product_id',), ['product.id'], ),
        sa.PrimaryKeyConstraint('product_id', 'component_id', name='product_component_pk')
    )
    op.create_table('product_variant',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(('product_id',), ['product.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_variant')
    op.drop_table('product_component')
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.drop_table('product')
    op.drop_table('maker')
    op.drop_table('component')
    # ### end Alembic commands ###
